import Container from "@/components/container";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className="flex flex-col w-full min-h-screen bg-slate-900 text-amber-100">
        <Header />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
